services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    environment:
      TZ: Asia/Singapore

      # New-API 使用 SQLite，不配置 SQL_DSN
      SESSION_SECRET: "dxqHdcY0zbOC8dPqqsyHw9RVXIobhcig5fkdRChp57Q84svOldTAT5d1eK5EpE5m"
      CRYPTO_SECRET: "CRe6uym99Ognok64OCNrlKC1NPcm9x8g5pn6OAHhaLPXnnxNGAfY26xv7TWjXRqg"

      FRONTEND_BASE_URL: "https://domaeng.com"

      # 防止长输出/流式输出太快超时
      STREAMING_TIMEOUT: "600"
      RELAY_TIMEOUT: "600"

      # 单机 SQLite 先不启用 Redis / 批量更新
      BATCH_UPDATE_ENABLED: "false"

    volumes:
      - ./new-api-data:/data
      - ./new-api-logs:/app/logs
    expose:
      - "3000"
    networks:
      - ai-gateway

  cliproxyapi:
    image: eceasy/cli-proxy-api:latest
    container_name: cliproxyapi
    restart: always
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./cliproxyapi/config.yaml:/CLIProxyAPI/config.yaml
      - ./cliproxyapi/auths:/root/.cli-proxy-api
      - ./cliproxyapi/logs:/CLIProxyAPI/logs
    expose:
      - "8317"

    # 只映射到服务器本机，公网不能直接访问
    # 用于你通过 SSH tunnel 管理 CLIProxyAPI
    ports:
      - "127.0.0.1:8317:8317"

    networks:
      - ai-gateway

  sora2api:
    image: thesmallhancat/sora2api:latest
    container_name: sora2api
    restart: always
    environment:
      TZ: Asia/Singapore
    expose:
      - "8000"
    volumes:
      - ./sora2api-data:/app/data
    networks:
      - ai-gateway

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    depends_on:
      - new-api
      - cliproxyapi
      - image-service
      - sora2api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
      - ./static:/usr/share/nginx/html/static:ro
    networks:
      - ai-gateway

networks:
  ai-gateway:
    driver: bridge
