services:
  new-api:
    image: calciumion/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    environment:
      TZ: Asia/Singapore
      SESSION_SECRET: "dxqHdcY0zbOC8dPqqsyHw9RVXIobhcig5fkdRChp57Q84svOldTAT5d1eK5EpE5m"
      CRYPTO_SECRET: "CRe6uym99Ognok64OCNrlKC1NPcm9x8g5pn6OAHhaLPXnnxNGAfY26xv7TWjXRqg"
      FRONTEND_BASE_URL: "https://domaeng.com"
      STREAMING_TIMEOUT: "600"
      RELAY_TIMEOUT: "600"
      BATCH_UPDATE_ENABLED: "false"
    volumes:
      - ./new-api-data:/data
      - ./new-api-logs:/app/logs
    expose:
      - "3000"
    networks:
      - ai-gateway

  cliproxyapi:
    image: eceasy/cli-proxy-api:latest
    container_name: cliproxyapi
    restart: always
    environment:
      TZ: Asia/Singapore
    volumes:
      - ./cliproxyapi/config.yaml:/CLIProxyAPI/config.yaml
      - ./cliproxyapi/auths:/root/.cli-proxy-api
      - ./cliproxyapi/logs:/CLIProxyAPI/logs
    expose:
      - "8317"
    ports:
      - "127.0.0.1:8317:8317"
    networks:
      - ai-gateway

  chatgpt2api:
    image: ghcr.io/basketikun/chatgpt2api:latest
    container_name: chatgpt2api
    restart: always
    environment:
      TZ: Asia/Singapore
      STORAGE_BACKEND: json
    volumes:
      - ./chatgpt2api-data:/app/data
      - ./chatgpt2api/config.json:/app/config.json
    expose:
      - "80"
    ports:
      - "127.0.0.1:8023:80"
    networks:
      - ai-gateway

networks:
  ai-gateway:
    driver: bridge
